spring:
    application:
        name: sportcenter
    datasource:
      url: jdbc:mysql://localhost:3307/sports-center
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
server:
  port: 8081
